// <auto-generated />
namespace EatOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Drugie_zmiany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Drugie_zmiany));
        
        string IMigrationMetadata.Id
        {
            get { return "201611141232313_Drugie_zmiany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
